export const runList = [
  {
    id: 1,
    title: "광주시청_2차 훈련",
    status: "훈련중",
    progressStep: 2,
    percent: 50,
    participants: "인포인 외 3건",
    template: "보안 안내 메일 외 3건",
    trainingPeriod: "2021.02.01 ~ 2021.02.12",
    educationPeriod: "2021.02.13 ~ 2021.02.15",
  },

  {
    id: 4,
    title: "인천시청_하반기 훈련",
    status: "훈련중",
    progressStep: 3,
    percent: 75,
    participants: "인천시 외 1건",
    template: "보안 교육 메일 외 1건",
    trainingPeriod: "2021.04.01 ~ 2021.04.12",
    educationPeriod: "2021.04.13 ~ 2021.04.15",
  },
  {
    id: 5,
    title: "대구시청_정기 훈련",
    status: "완료",
    progressStep: 4,
    percent: 100,
    participants: "대구시 외 4건",
    template: "정기 보안 메일 외 2건",
    trainingPeriod: "2021.05.01 ~ 2021.05.10",
    educationPeriod: "2021.05.11 ~ 2021.05.13",
  },
];

export const statusText = ["대기", "메일발송", "훈련중", "교육중"];

export const dummyData = [
  {
    name: "홍길동",
    department: "보안팀",
    position: "사원",
    emailReceivedAt: "hong@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "O",
    phishingInputAt: "X",
    reportSubmittedAt: "O",
    status: "완료",
  },
  {
    name: "이예진",
    department: "개발팀",
    position: "주임",
    emailReceivedAt: "yejin@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "X",
    attachmentDownloadedAt: "X",
    phishingInputAt: "X",
    reportSubmittedAt: "X",
    status: "진행중",
  },
  {
    name: "김민수",
    department: "기획팀",
    position: "대리",
    emailReceivedAt: "minsoo@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "X",
    phishingInputAt: "O",
    reportSubmittedAt: "O",
    status: "완료",
  },
  {
    name: "박지현",
    department: "영업팀",
    position: "과장",
    emailReceivedAt: "jihyun@company.com",
    emailOpenedAt: "X",
    linkClickedAt: "X",
    attachmentDownloadedAt: "X",
    phishingInputAt: "X",
    reportSubmittedAt: "X",
    status: "미열람",
  },
  {
    name: "최유진",
    department: "마케팅팀",
    position: "사원",
    emailReceivedAt: "yujin@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "O",
    phishingInputAt: "O",
    reportSubmittedAt: "O",
    status: "완료",
  },
  {
    name: "정하늘",
    department: "디자인팀",
    position: "주임",
    emailReceivedAt: "haneul@company.com",
    emailOpenedAt: "X",
    linkClickedAt: "X",
    attachmentDownloadedAt: "X",
    phishingInputAt: "X",
    reportSubmittedAt: "X",
    status: "미열람",
  },
  {
    name: "오세훈",
    department: "인사팀",
    position: "차장",
    emailReceivedAt: "sehoon@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "X",
    attachmentDownloadedAt: "X",
    phishingInputAt: "X",
    reportSubmittedAt: "X",
    status: "진행중",
  },
  {
    name: "강수진",
    department: "총무팀",
    position: "대리",
    emailReceivedAt: "soojin@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "O",
    phishingInputAt: "X",
    reportSubmittedAt: "X",
    status: "진행중",
  },
  {
    name: "조성우",
    department: "회계팀",
    position: "사원",
    emailReceivedAt: "sungwoo@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "X",
    attachmentDownloadedAt: "X",
    phishingInputAt: "X",
    reportSubmittedAt: "O",
    status: "완료",
  },
  {
    name: "윤서연",
    department: "법무팀",
    position: "과장",
    emailReceivedAt: "seoyeon@company.com",
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "O",
    phishingInputAt: "X",
    reportSubmittedAt: "X",
    status: "진행중",
  },
];

export const dummyEData = [
  {
    name: "홍길동",
    department: "보안팀",
    position: "사원",
    emailReceivedAt: "hong@company.com",
    result: "이수",
    status: "완료",
  },
  {
    name: "이예진",
    department: "개발팀",
    position: "주임",
    emailReceivedAt: "yejin@company.com",
    result: "미이수",
    status: "진행중",
  },
  {
    name: "김민수",
    department: "기획팀",
    position: "대리",
    emailReceivedAt: "minsoo@company.com",
    result: "이수",
    status: "완료",
  },
  {
    name: "박지현",
    department: "영업팀",
    position: "과장",
    emailReceivedAt: "jihyun@company.com",
    result: "미이수",
    status: "미열람",
  },
  {
    name: "최유진",
    department: "마케팅팀",
    position: "사원",
    emailReceivedAt: "yujin@company.com",
    result: "이수",
    status: "완료",
  },
];

export const runTableBtn = [
  {
    label: "대상자 그룹 필터링",
    img: "/images/tool_filter.svg",
  },
  {
    label: "미발송자 재발송",
    img: "/images/tool_ccw.svg",
    style: "printer",
  },
];

//

export const DepDummyData = [
  {
    department: "보안팀",
    num: 5,
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "X",
    phishingInputAt: "X",
    reportSubmittedAt: "O",
    educationCompletedAt: "O",
  },
  {
    department: "개발팀",
    num: 12,
    emailOpenedAt: "X",
    linkClickedAt: "X",
    attachmentDownloadedAt: "X",
    phishingInputAt: "O",
    reportSubmittedAt: "X",
    educationCompletedAt: "X",
  },
  {
    department: "인사팀",
    num: 8,
    emailOpenedAt: "O",
    linkClickedAt: "O",
    attachmentDownloadedAt: "O",
    phishingInputAt: "O",
    reportSubmittedAt: "O",
    educationCompletedAt: "O",
  },
];
