export const templateList = [
  {
    id: 1,
    name: "세금 미납 안내 템플릿",
    type: "링크클릭",
    subject: "세금 미납 확인 부탁드립니다.",
    fromName: "국세청",
    fromEmail: "hfeioflo@naver.com",
    thumbnailUrl: "/images/thumbnail_tax_template.png",
  },
  {
    id: 2,
    name: "출석 요청 템플릿",
    type: "메일열람",
    subject: "회의 출석 요청드립니다.",
    fromName: "총무팀",
    fromEmail: "admin@company.com",
    thumbnailUrl: "/images/thumbnail_meeting_template.png",
  },
  {
    id: 3,
    name: "급여명세서 안내 템플릿",
    type: "링크클릭",
    subject: "이번 달 급여 명세서를 확인해주세요.",
    fromName: "회계팀",
    fromEmail: "payroll@company.com",
    thumbnailUrl: "/images/thumbnail_pay_template.png",
  },
  {
    id: 4,
    name: "계정 비밀번호 변경 템플릿",
    type: "메일열람",
    subject: "보안을 위해 비밀번호를 변경해주세요.",
    fromName: "보안팀",
    fromEmail: "security@company.com",
    thumbnailUrl: "/images/thumbnail_security_template.png",
  },
  {
    id: 5,
    name: "출장비 내역 확인 템플릿",
    type: "링크클릭",
    subject: "출장비 내역을 확인 후 회신 바랍니다.",
    fromName: "관리팀",
    fromEmail: "manager@company.com",
    thumbnailUrl: "/images/thumbnail_expense_template.png",
  },
  {
    id: 6,
    name: "사내 이벤트 안내 템플릿",
    type: "메일열람",
    subject: "사내 이벤트에 참여해주세요!",
    fromName: "홍보팀",
    fromEmail: "pr@company.com",
    thumbnailUrl: "/images/thumbnail_event_template.png",
  },
  {
    id: 7,
    name: "전자계약서 확인 템플릿",
    type: "링크클릭",
    subject: "전자계약서를 확인 후 서명 부탁드립니다.",
    fromName: "계약관리팀",
    fromEmail: "contract@company.com",
    thumbnailUrl: "/images/thumbnail_contract_template.png",
  },
  {
    id: 8,
    name: "보안 정책 변경 안내 템플릿",
    type: "메일열람",
    subject: "보안 정책이 변경되었습니다. 확인해주세요.",
    fromName: "IT팀",
    fromEmail: "itpolicy@company.com",
    thumbnailUrl: "/images/thumbnail_policy_template.png",
  },
];
